# Makefile

main: MusicScript.applescript SpotifyScript.applescript
	osacompile -o ../MusicScript.scpt MusicScript.applescript
	echo "Apple Music Applescript compiled"
	osacompile -o ../SpotifyScript.scpt SpotifyScript.applescript
	echo "Spotify Applescript compiled"
